apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  app: <%= projectName %>
  namespace: <%= namespaceName %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: <%= projectName %>
    spec:
      containers:
      - name: example
        image: nginx:stable
