apiVersion: v1
kind: Service
metadata:
  app: <%= projectName %>
  namespace: <%= namespaceName %>
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: <%= projectName %>
